version: "3"
services:
  web:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - webnet

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    networks:
      - webnet


networks:
  webnet:
